"""End-to-end recovery tests: can we get the parameters back out?

These are the tests that matter most for the empirical part of the paper.  If
the estimator cannot recover known parameters from synthetic data, nothing it
says about SPY means anything.
"""

import numpy as np
import pandas as pd
import pytest

from vg import VGParams, implied_vol, vg_call_esscher_fourier
from vg.calibration import calibrate, price_quotes
from vg.estimation import fit_mle, moment_estimates

TRUE = VGParams(theta=-0.16, sigma=0.13, nu=0.25)
DT = 1.0 / 252.0


def _synthetic_returns(n=8000, mu=0.07, seed=0):
    from vg.process import simulate_terminal

    rng = np.random.default_rng(seed)
    return mu * DT + simulate_terminal(TRUE, DT, n, rng)


def test_moment_estimator_recovers_parameters():
    r = _synthetic_returns(n=60_000, seed=1)
    fit = moment_estimates(r, DT)
    assert fit.success
    assert fit.params.sigma == pytest.approx(TRUE.sigma, rel=0.10)
    assert fit.params.nu == pytest.approx(TRUE.nu, rel=0.30)
    assert fit.params.theta == pytest.approx(TRUE.theta, rel=0.40)


def test_moment_estimator_reproduces_the_sample_moments():
    """Whatever it recovers, the fitted moments must match the sample ones."""
    r = _synthetic_returns(n=20_000, seed=2)
    fit = moment_estimates(r, DT)
    for key in ["var", "skewness", "excess_kurtosis"]:
        assert fit.fitted[key] == pytest.approx(fit.sample[key], rel=1e-4, abs=1e-9)


def test_mle_recovers_parameters_when_the_gamma_shape_is_order_one():
    """MLE is trustworthy when dt/nu is O(1) -- here monthly steps, dt/nu = 1/3."""
    from vg.process import simulate_terminal

    dt = 1.0 / 12.0
    true = VGParams(theta=-0.16, sigma=0.13, nu=0.25)
    rng = np.random.default_rng(21)
    r = 0.07 * dt + simulate_terminal(true, dt, 20_000, rng)

    mle = fit_mle(r, dt)
    assert mle.params.sigma == pytest.approx(true.sigma, rel=0.10)
    assert mle.params.nu == pytest.approx(true.nu, rel=0.25)
    assert mle.params.theta == pytest.approx(true.theta, rel=0.40)


def test_mle_beats_the_moment_estimator_on_its_own_criterion():
    """Whatever it recovers, the MLE must not be dominated on the likelihood."""
    from vg.process import log_density

    r = _synthetic_returns(n=20_000, seed=3)
    mom = moment_estimates(r, DT)
    mle = fit_mle(r, DT)
    ll_mom = float(np.sum(log_density(mom.params, r - mom.mu * DT, DT)))
    assert mle.loglik >= ll_mom - 1e-6


def test_mle_overestimates_nu_at_daily_frequency():
    """Document the pathology rather than hide it.

    At dt/nu ~ 0.02 the VG density has a power singularity at the origin and
    over 60% of a simulated daily sample lands within 1e-8 of the drift.  The
    likelihood is then driven by how sharply a parameter set spikes at the mode
    and prefers a much larger nu than the one that generated the data, while the
    moment estimator is unaffected.  If this test ever starts failing because
    the MLE became accurate here, the module docstring needs updating too.
    """
    r = _synthetic_returns(n=20_000, seed=3)
    assert DT / TRUE.nu < 0.05
    assert np.mean(np.abs(r - 0.07 * DT) < 1e-8) > 0.5

    mom = moment_estimates(r, DT)
    mle = fit_mle(r, DT)

    assert mom.params.nu == pytest.approx(TRUE.nu, rel=0.30)
    assert mle.params.nu > 3.0 * TRUE.nu


def test_estimators_reject_tiny_samples():
    with pytest.raises(ValueError, match="at least 50"):
        moment_estimates(np.zeros(10), DT)


# --------------------------------------------------------------------------- #
# Calibration
# --------------------------------------------------------------------------- #


def _synthetic_chain(params=TRUE, spot=100.0, r=0.03, q=0.015):
    """A clean option chain generated by the model itself."""
    rows = []
    for T in [0.08, 0.25, 0.5, 1.0]:
        fwd = spot * np.exp((r - q) * T)
        strikes = np.round(fwd * np.linspace(0.85, 1.15, 13), 2)
        prices = np.asarray(vg_call_esscher_fourier(spot, strikes, r, T, params, q))
        for k, price in zip(strikes, prices):
            iv = implied_vol(float(price), spot, float(k), r, T, q)
            rows.append(
                {
                    "expiry": f"T{T}",
                    "T": T,
                    "strike": float(k),
                    "spot": spot,
                    "r": r,
                    "q": q,
                    "price": float(price),
                    "iv": iv,
                }
            )
    return pd.DataFrame(rows).dropna(subset=["iv"])


def test_esscher_calibration_recovers_the_risk_neutral_parameters():
    """Synthetic chain in, generating *risk-neutral* parameters out.

    What can be recovered is (sigma_Q, nu), not the physical (theta, sigma, nu):
    the martingale condition makes theta unidentifiable under this
    specification, so asking the calibration to return the physical theta that
    happened to generate the chain would be asking for something the prices do
    not contain.  What must hold is that the fitted measure reprices the chain
    and agrees with the generating one on the parameters that are observable.
    """
    from vg.esscher import risk_neutral_params as rn

    chain = _synthetic_chain()
    res = calibrate(chain, "esscher")

    assert res.free_parameters == ("sigma", "nu")
    true_q = rn(TRUE, 0.03 - 0.015)[0]
    fitted_q = res.risk_neutral_params(0.03 - 0.015)

    assert fitted_q.sigma == pytest.approx(true_q.sigma, rel=0.02)
    assert fitted_q.theta == pytest.approx(true_q.theta, rel=0.05, abs=1e-4)
    assert res.params.nu == pytest.approx(TRUE.nu, rel=0.10)
    assert res.rmse_iv < 1e-4          # under 1 basis point of vol
    assert res.rmse_price < 1e-3


def test_calibration_diagnostics_are_populated():
    res = calibrate(_synthetic_chain(), "esscher")
    q = res.quotes
    for col in ["model_price", "price_error", "model_iv", "iv_error"]:
        assert col in q.columns
    assert np.isfinite(q["model_iv"]).all()
    assert len(q) == res.n_quotes


def test_price_quotes_matches_row_by_row_pricing():
    """Grouping quotes by expiry must not change any price.

    Tolerance is 5e-6 rather than machine epsilon because the shared quadrature
    grid is sized by the widest log-moneyness in the group, so the shortest
    expiry (T/nu = 0.32 here, the heavy-tailed regime) resolves slightly
    differently than it would alone.  Measured, that difference is about 1e-6
    for T/nu = 0.32 and below 1e-10 for every other expiry -- four orders of
    magnitude under the bid-ask spread of any real quote, and inside the error
    the quadrature itself reports.
    """
    chain = _synthetic_chain()
    grouped = price_quotes(chain, TRUE, "esscher")
    one_by_one = np.array(
        [
            vg_call_esscher_fourier(
                float(row.spot), float(row.strike), float(row.r), float(row["T"]), TRUE, float(row.q)
            )
            for _, row in chain.iterrows()
        ]
    )
    assert np.abs(grouped - one_by_one).max() < 5e-6


def test_calibration_rejects_a_tiny_chain():
    with pytest.raises(ValueError, match="at least 5 quotes"):
        calibrate(_synthetic_chain().head(3), "esscher")


def test_unknown_measure_is_rejected():
    with pytest.raises(ValueError, match="unknown measure"):
        price_quotes(_synthetic_chain(), TRUE, "nonsense")
